import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocument } from "@/components/legal/legal-document";

export const metadata: Metadata = { title: "Privacy Policy | ReachFlow", description: "How ReachFlow collects, uses, shares, and protects personal information." };

export default function PrivacyPage() {
  return <LegalDocument eyebrow="Legal" title="Privacy Policy" summary="This policy explains how ReachFlow handles information when people visit our website, create an account, use the CRM, submit a ReachFlow-hosted form, or connect another service.">
    <section><h2>1. Who this policy covers</h2><p>ReachFlow provides customer relationship management, outreach organization, lead capture, automation, and related services. For account, billing, website, and service-operation information, ReachFlow acts as the organization deciding why and how that information is processed.</p><p>For prospect, lead, message, form-response, and customer-contact information uploaded or collected by a ReachFlow customer, that customer normally decides why and how the information is used. ReachFlow processes it on the customer&apos;s instructions. If an organization contacted you using ReachFlow, contact that organization first about its use of your information.</p></section>
    <section><h2>2. Information we collect</h2><ul><li><strong>Account information:</strong> name, email address, authentication identifiers, workspace membership, role, and profile preferences.</li><li><strong>Workspace and CRM information:</strong> agency details, prospects, business contact information, notes, tasks, deals, campaigns, attribution, messages, scoring information, and custom fields.</li><li><strong>Form information:</strong> fields submitted through a hosted form, the consent statement accepted, submission time, referrer, browser information, and a one-way IP-derived fingerprint used for abuse prevention. ReachFlow does not store the raw IP address in its hosted-form submission record.</li><li><strong>Integration information:</strong> connection configuration, provider identifiers, webhook events, delivery results, and encrypted credentials where a connected feature requires them.</li><li><strong>Usage and technical information:</strong> device and browser details, session information, security events, feature usage, errors, and diagnostic logs.</li><li><strong>Communications:</strong> support requests, feedback, and other messages sent to us.</li></ul></section>
    <section><h2>3. Where information comes from</h2><p>We receive information directly from account holders and form respondents, from workspace administrators and authorized team members, from connected services, from customer-configured webhooks and imports, and automatically when the service is used. Customers may also add business contact information obtained from public or other lawful sources. Customers are responsible for having a lawful basis to place that information in ReachFlow and use it for outreach.</p></section>
    <section><h2>4. How we use information</h2><ul><li>Provide, secure, maintain, and troubleshoot ReachFlow.</li><li>Create and match prospects, record attribution and consent, operate workflows, and deliver customer-requested integrations.</li><li>Authenticate users, prevent abuse, enforce limits, and investigate security incidents.</li><li>Generate requested AI-assisted content and return it to the user.</li><li>Communicate about the service, support requests, operational changes, and legally required notices.</li><li>Analyze aggregated or de-identified usage to improve reliability and product decisions.</li><li>Comply with legal obligations and protect the rights and safety of users, ReachFlow, and others.</li></ul></section>
    <section><h2>5. Legal bases where applicable</h2><p>Depending on the context and applicable law, processing may be necessary to perform a contract, comply with law, protect legitimate interests such as service security and improvement, or rely on consent. Consent can be withdrawn for future processing. A ReachFlow customer is responsible for identifying its own lawful basis for prospecting, marketing, and customer communications.</p></section>
    <section><h2>6. How information is shared</h2><p>We may disclose information to infrastructure, database, authentication, email, AI, monitoring, and other vendors that process information to provide the service; to integrations explicitly enabled by a workspace; to workspace members according to their permissions; during a corporate transaction; when required by law; or to protect legal rights and safety.</p><p>ReachFlow does not sell personal information or share it for cross-context behavioral advertising. We do not disclose customer CRM content to third parties for their independent marketing.</p></section>
    <section><h2>7. AI-assisted features</h2><p>When a user invokes an AI feature, the prompt and relevant context may be sent to an AI service provider to generate the requested output. Users should review outputs before use and should not submit sensitive information unless it is necessary and permitted. ReachFlow does not represent that generated content is error-free, unique, or legally suitable for a particular outreach campaign.</p></section>
    <section><h2>8. Cookies and local storage</h2><p>ReachFlow uses cookies and browser storage needed for authentication, security, session continuity, and saved interface preferences. We do not currently use third-party advertising cookies on the ReachFlow website. If that changes, this policy and any required consent controls will be updated.</p></section>
    <section><h2>9. Retention</h2><p>Information is kept for as long as needed to provide the service, satisfy customer-configured retention settings, resolve disputes, maintain security and audit history, and comply with law. Customers control much of their CRM content and can delete records through available product controls. Backups and security records may persist for a limited period before routine deletion. Minimal suppression evidence may be retained where necessary to honor a do-not-contact request.</p></section>
    <section><h2>10. Security and international processing</h2><p>We use administrative, technical, and organizational safeguards designed to protect information, including access controls, tenant isolation, encryption for supported credentials, and audit records. No method of storage or transmission is completely secure. Service providers may process information in countries other than where a user lives; where required, appropriate transfer safeguards should be used.</p></section>
    <section><h2>11. Your choices and rights</h2><p>Depending on where you live, you may be entitled to request access, correction, deletion, restriction, objection, portability, withdrawal of consent, or an appeal, and to complain to a data-protection authority. You will not be discriminated against for exercising applicable privacy rights. We may need to verify your identity and authority before acting.</p><p>See the <Link href="/data-deletion">Data Deletion page</Link> for request instructions. Workspace users should send requests from the email associated with their account. Prospects and form respondents should identify the organization that collected their information when possible.</p></section>
    <section><h2>12. Children</h2><p>ReachFlow is a business service and is not directed to children. We do not knowingly collect personal information from children through our own account-registration process. Customers must not use ReachFlow to collect children&apos;s information without all permissions required by law.</p></section>
    <section><h2>13. Changes and contact</h2><p>We may update this policy as the service or law changes. Material updates will be identified by a new effective date and, where appropriate, an in-product or email notice.</p><p>Questions and privacy requests can be sent to <a href="mailto:privacy@reachflow.app">privacy@reachflow.app</a>.</p></section>
  </LegalDocument>;
}
