import { addAttribution, recalculateScore } from "@/app/actions/revenue"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

type Attribution = { id:string; provider:string; source_name:string; campaign_name:string|null; utm_source:string|null; utm_medium:string|null; utm_campaign:string|null; captured_at:string; is_original:boolean }
type Score = { score:number; band:string; breakdown:Array<{name:string;points:number;reason:string}>; calculated_at:string } | null

export function ProspectRevenueIntelligence({prospectId,attributions,score,canEdit}:{prospectId:string;attributions:Attribution[];score:Score;canEdit:boolean}){
 const original=attributions.find(a=>a.is_original); const latest=attributions[0]
 const bandClass=score?.band==="hot"?"bg-rose-500/10 text-rose-700":score?.band==="warm"?"bg-amber-500/10 text-amber-700":"bg-sky-500/10 text-sky-700"
 return <div className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center justify-between">Lead score {score&&<span className={`rounded-full px-3 py-1 text-sm font-semibold uppercase ${bandClass}`}>{score.score} · {score.band}</span>}</CardTitle></CardHeader><CardContent className="space-y-3">{score?<>{score.breakdown.length?<div className="space-y-2">{score.breakdown.map((item,i)=><div key={`${item.name}-${i}`} className="flex items-start justify-between rounded-lg bg-muted/50 p-2.5"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.reason}</p></div><b className={item.points>=0?"text-emerald-600":"text-destructive"}>{item.points>0?"+":""}{item.points}</b></div>)}</div>:<p className="text-sm text-muted-foreground">No rules currently match this prospect.</p>}<p className="text-xs text-muted-foreground">Calculated {new Date(score.calculated_at).toLocaleString()}</p></>:<p className="text-sm text-muted-foreground">No score calculated yet. Configure scoring rules, then calculate the score.</p>}{canEdit&&<form action={recalculateScore}><input type="hidden" name="prospect_id" value={prospectId}/><Button variant="outline" size="sm">Recalculate score</Button></form>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Lead-source attribution</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-muted/50 p-3"><p className="text-xs text-muted-foreground">Original source</p><p className="font-medium">{original?.source_name??"Unknown"}</p></div><div className="rounded-lg bg-muted/50 p-3"><p className="text-xs text-muted-foreground">Latest source</p><p className="font-medium">{latest?.source_name??"Unknown"}</p></div></div>{attributions.length>0&&<div className="space-y-2">{attributions.map(a=><div key={a.id} className="border-l-2 pl-3 text-sm"><p className="font-medium">{a.source_name} {a.is_original&&<span className="text-xs text-primary">Original</span>}</p><p className="text-xs text-muted-foreground">{a.provider}{a.campaign_name?` · ${a.campaign_name}`:""} · {new Date(a.captured_at).toLocaleDateString()}</p></div>)}</div>}{canEdit&&<form action={addAttribution} className="grid gap-2 sm:grid-cols-2"><input type="hidden" name="prospect_id" value={prospectId}/><select name="provider" className="h-8 rounded-lg border bg-background px-2 text-sm"><option value="manual">Manual</option><option value="referral">Referral</option><option value="website">Website</option><option value="import">Import</option><option value="event">Event</option><option value="partner">Partner</option></select><Input name="source_name" placeholder="Source name" required/><Input name="campaign_name" placeholder="Campaign name"/><Input name="landing_page" placeholder="Landing page URL"/><Input name="utm_source" placeholder="UTM source"/><Input name="utm_medium" placeholder="UTM medium"/><Input name="utm_campaign" placeholder="UTM campaign"/><Button className="sm:col-span-2">Add attribution touchpoint</Button></form>}</CardContent></Card></div>
}
