export type RoadmapEffort = "Small" | "Medium" | "Medium–large" | "Large"
export type RoadmapValue = "High" | "Very high" | "Required for launch"

export type RoadmapExternalRequirement = {
  service: string
  purpose: string
  setup: string[]
  credentials: string[]
  webhooks?: string[]
}

export type RoadmapFeature = {
  key: string
  order: number
  phase: 1 | 2 | 3
  title: string
  tagline: string
  effort: RoadmapEffort
  value: RoadmapValue
  estimatedDelivery: string
  problem: string
  outcome: string
  workflows: string[]
  existingIntegration: string[]
  userInterface: string[]
  dataModel: string[]
  backend: string[]
  security: string[]
  analytics: string[]
  edgeCases: string[]
  testing: string[]
  dependencies: string[]
  risks: string[]
  rollout: string[]
  acceptanceCriteria: string[]
  externalRequirements: RoadmapExternalRequirement[]
}

export const ROADMAP_PHASES = [
  { id: 1 as const, title: "Existing-code extensions", description: "Features built primarily from the current prospect, outreach, team, campaign, analytics, and Supabase foundations." },
  { id: 2 as const, title: "Controlled reporting and outbound connections", description: "Public reporting surfaces and outbound integrations that require stronger operational and delivery controls." },
  { id: 3 as const, title: "External services and provider integrations", description: "OAuth, provider APIs, inbound webhooks, payment processing, and integrations with external reliability requirements." },
]

const local = (feature: Omit<RoadmapFeature, "externalRequirements">): RoadmapFeature => ({ ...feature, externalRequirements: [] })

export const ROADMAP_FEATURES: RoadmapFeature[] = [
  local({
    key: "call_outcomes", order: 1, phase: 1, title: "Call outcomes", tagline: "Turn every call attempt into structured, reportable outreach data.", effort: "Small", value: "High", estimatedDelivery: "3–5 engineering days",
    problem: "ReachFlow can store call notes, but a free-form note cannot reliably distinguish a connected call from no answer, voicemail, a wrong number, or a requested callback. Teams cannot report call effectiveness or determine the correct next action consistently.",
    outcome: "Every recorded call has a standardized result, optional duration, next action, and follow-up date while still retaining narrative notes in the unified outreach history.",
    workflows: ["Choose Call in the outreach composer, select an outcome, record notes and optional duration, then set the next follow-up before saving.", "A connected call can move the prospect to waiting or replied; callback requested creates a dated follow-up; wrong number flags the phone identity for correction.", "Managers filter call activity by user, campaign, date, and outcome."],
    existingIntegration: ["Extend messages with call-specific metadata without creating a separate conversation timeline.", "Continue updating prospects.last_contacted_at and activity_log when the call is recorded.", "Use current assignee, campaign, notification, and analytics relationships."],
    userInterface: ["Conditional call-outcome controls in OutreachComposer.", "Outcome badge, duration, and next action in prospect history and Messages page.", "Call outcome filters and a compact call-performance analytics section."],
    dataModel: ["Add call_outcome, call_duration_seconds, callback_at, and next_action to messages or a one-to-one message_call_details table.", "Constrain outcomes to connected, no_answer, voicemail, callback_requested, wrong_number, and disqualified.", "Index call outcome and callback date for operational views."],
    backend: ["Create a validated recordCall server action that writes message and prospect follow-up changes consistently.", "Log old/new follow-up values and call outcome.", "Prevent non-call message types from accepting call metadata."],
    security: ["Use existing organization-scoped message and prospect RLS.", "Editors and admins write calls; viewers remain read-only."],
    analytics: ["Connection rate, voicemail rate, callback rate, average connected duration, calls per representative, and booked-after-call conversion."],
    edgeCases: ["Duration omitted for no-answer outcomes.", "Callback date in the past or outside organization timezone.", "Prospect deleted while a call form is open."],
    testing: ["Schema constraints for incompatible message types.", "Server-action authorization and organization isolation.", "Composer validation, history rendering, and timezone tests."],
    dependencies: ["Existing messages table, outreach composer, prospect follow-up timestamp, and activity log."],
    risks: ["Overloading messages with too many channel-specific columns; use an extension table if metadata expands."],
    rollout: ["Add schema and record action.", "Release composer and timeline rendering.", "Add filters and analytics after sufficient data exists."],
    acceptanceCriteria: ["All call attempts require an outcome.", "Callback requests create a visible follow-up.", "Call data appears chronologically with other outreach.", "Managers can report calls by outcome and user."],
  }),
  local({
    key: "reply_objection_tracking", order: 2, phase: 1, title: "Reply and objection tracking", tagline: "Capture what prospects said and why opportunities advance or stop.", effort: "Medium", value: "High", estimatedDelivery: "1–2 weeks",
    problem: "The pipeline knows that a prospect replied, but not what the reply meant. Free-form notes cannot support consistent objection reporting, targeting improvements, or automatic sequence stopping.",
    outcome: "Inbound replies become first-class timeline events with intent, sentiment, objection, qualification, and next-step metadata.",
    workflows: ["Record an inbound reply from the prospect detail panel, choose channel and received time, paste the content, then classify intent.", "Interested replies stop active sequences, update status, notify the assignee, and optionally create a follow-up task.", "Not-now replies require a revisit date; disqualified replies require a reason; wrong-contact replies preserve the history without treating the contact as qualified."],
    existingIntegration: ["Extend the unified message history to distinguish inbound from outbound direction.", "Use existing sequence cancellation, status updates, notifications, and activity logging.", "Feed structured outcomes into campaign and team analytics."],
    userInterface: ["Record reply action adjacent to Record outreach.", "Direction-aware timeline styling and reply detail drawer.", "Objection and reply-intent filters in Prospects, Messages, and Analytics."],
    dataModel: ["Add direction, reply_intent, objection_code, received_at, and recorded_by fields to messages or introduce conversation_events.", "Maintain a controlled objection vocabulary with optional organization-defined values.", "Track the status transition caused by the reply in activity_log."],
    backend: ["Transactional recordReply action coordinates event insertion, sequence cancellation, status, reminder, and notification.", "Validation requires revisit date for not_now and reason for disqualified.", "Provide aggregate queries for intent and objection conversion."],
    security: ["Only organization members see replies; viewers cannot create or edit them.", "Sanitize stored content for display and enforce maximum sizes."],
    analytics: ["Positive reply rate, objection distribution, reply-to-booked conversion, time to first reply, and performance by source/message type."],
    edgeCases: ["Multiple replies received before recording.", "Reply entered against a closed prospect.", "Deleting or correcting a reply that caused a status transition."],
    testing: ["Atomic status/sequence behavior.", "Conditional validation for each intent.", "Analytics denominators and historical correction tests."],
    dependencies: ["Messages, activity log, notifications, sequences, and prospect status actions."],
    risks: ["Manual classification becomes inconsistent if the vocabulary is too large; start with a constrained taxonomy."],
    rollout: ["Ship manual reply capture first.", "Add analytics after teams accumulate data.", "Reuse the model later for provider-synchronized inbound replies."],
    acceptanceCriteria: ["Replies appear as inbound timeline entries.", "Positive replies stop active sequences reliably.", "Required next actions are enforced.", "Reply and objection analytics are filterable by campaign and owner."],
  }),
  local({
    key: "follow_up_command_center", order: 3, phase: 1, title: "Follow-up command center", tagline: "Give every user a focused daily queue of prospects requiring action.", effort: "Medium", value: "Very high", estimatedDelivery: "1–2 weeks",
    problem: "Users currently navigate the whole pipeline to discover overdue or neglected prospects. A CRM becomes habitual when it clearly answers what should be done next every morning.",
    outcome: "A dedicated workspace ranks overdue, due-today, unanswered, recently replied, and stale prospects and supports rapid completion without leaving the queue.",
    workflows: ["Open Today to see a prioritized personal queue; admins can switch to the whole organization.", "Open a queue item, review recent history, record the action, reschedule or resolve it, then advance automatically to the next prospect.", "Snooze valid prospects with a required reason and date; bulk reassign unowned items."],
    existingIntegration: ["Build on prospects.follow_up_at, assigned_to, last_contacted_at, status, messages, call outcomes, and reply tracking.", "Reuse prospect detail components and server actions rather than duplicating mutation logic.", "Link digest-email items directly to the corresponding queue entry."],
    userInterface: ["New /today page and primary sidebar item.", "Queue tabs, urgency indicators, keyboard-friendly next-item navigation, inline actions, and empty-state completion summary.", "Admin owner and campaign filters."],
    dataModel: ["Prefer derived queue queries initially; add snoozed_until, snooze_reason, and resolved_at only where existing fields are insufficient.", "Define stale thresholds in organization settings."],
    backend: ["One query/service produces deterministic queue categories and priority.", "Actions revalidate Today, Pipeline, Prospect, and Analytics views.", "Prevent duplicate categorization or document deliberate overlaps."],
    security: ["Editors see their assignments by default; admins can see all; organization RLS remains authoritative."],
    analytics: ["Queue completion rate, overdue aging, average time to action, snooze rate, and follow-up-to-reply conversion."],
    edgeCases: ["Timezone boundary for due today.", "Unassigned prospect visibility.", "Prospect appearing in multiple categories.", "Concurrent action by another team member."],
    testing: ["Timezone and priority ordering.", "Role-specific queue scope.", "Action-to-next-item behavior and empty states."],
    dependencies: ["Call outcomes and reply classification improve queue accuracy but the first version can use current data."],
    risks: ["An opaque ranking system damages trust; publish the priority rules in the UI."],
    rollout: ["Start with overdue and due-today.", "Add stale and unanswered rules.", "Add user-configurable thresholds after usage evidence."],
    acceptanceCriteria: ["Users can complete a day’s follow-ups from one page.", "Queue ordering is deterministic and timezone-correct.", "Each action removes or reclassifies the prospect immediately.", "Admins can inspect team-wide backlog."],
  }),
  local({
    key: "saved_views_smart_lists", order: 4, phase: 1, title: "Saved views and smart lists", tagline: "Turn complex filters into reusable operational views.", effort: "Medium", value: "High", estimatedDelivery: "1–2 weeks",
    problem: "Teams repeatedly reconstruct the same filters and cannot share standardized working lists such as overdue regional leads or booked prospects missing deal values.",
    outcome: "Users save named query definitions that update automatically and can be private or shared with the organization.",
    workflows: ["Apply filters on Prospects or Pipeline, choose Save view, name it, and select private or shared visibility.", "Open a saved view from the sidebar or view selector; optionally set it as the default.", "Admins manage shared views and repair filters whose referenced tags or users were deleted."],
    existingIntegration: ["Serialize existing status, platform, owner, campaign, tag, search, country, state, date, and activity filters.", "Reuse list and export behavior so exports honor the active saved view."],
    userInterface: ["View selector above filters, save/update-as-new controls, and Saved views settings area.", "Smart count indicators calculated on demand, not stored."],
    dataModel: ["saved_views: id, org_id, owner_id, name, scope, entity_type, filter_version, filter_json, is_default, timestamps.", "Unique private names per owner and shared names per organization."],
    backend: ["Version and validate filter JSON with Zod.", "Translate only allowlisted filter operators into Supabase queries.", "Provide create, update, duplicate, delete, and default-view actions."],
    security: ["Private views readable only by owner; shared views by organization; shared mutation admin-only or configurable."],
    analytics: ["Optional product analytics: most-used views and zero-result views; no customer data copied into telemetry."],
    edgeCases: ["Deleted referenced tag/campaign/user.", "Filter schema upgrades.", "Two default views for the same user/entity."],
    testing: ["Filter serialization round trips.", "RLS for private/shared scope.", "Backward-compatible filter migrations and URL synchronization."],
    dependencies: ["Existing prospect filters and export filters."],
    risks: ["Arbitrary JSON operators can create security or performance problems; use a strict schema and bounded filters."],
    rollout: ["Support current filters first.", "Add advanced activity/date filters.", "Add curated system views for common workflows."],
    acceptanceCriteria: ["Saved views reproduce the same results after reload.", "Shared and private visibility is enforced.", "Deleted dependencies degrade gracefully.", "Exports respect the active view."],
  }),
  local({
    key: "tasks_team_handoffs", order: 5, phase: 1, title: "Tasks and team handoffs", tagline: "Coordinate internal work that is not itself an outreach event.", effort: "Medium", value: "High", estimatedDelivery: "1–2 weeks",
    problem: "A follow-up date represents contacting a prospect, but agency work also includes research, proposal preparation, approvals, and handoffs between people.",
    outcome: "Members create, assign, prioritize, complete, and discuss tasks connected to prospects or campaigns.",
    workflows: ["Create a task from a prospect, campaign, or My tasks; assign it with due date and priority.", "The assignee receives an in-app notification and sees it in My tasks.", "Completing, reassigning, or commenting on a task creates an auditable event; overdue tasks surface in Today."],
    existingIntegration: ["Use organization members, notifications, activity logging, prospect/campaign links, and Today queue.", "Show open tasks in prospect detail without mixing them into message history."],
    userInterface: ["/tasks page with My tasks, created by me, overdue, and completed views.", "Inline task panel in prospect and campaign detail.", "Create/edit sheet with title, description, assignee, priority, and due date."],
    dataModel: ["tasks table with org, prospect/campaign nullable references, creator, assignee, title, description, status, priority, due/completed timestamps.", "task_comments and task_activity tables if discussion is included in v1."],
    backend: ["Validated CRUD actions plus complete, reopen, assign, and comment actions.", "Notification fan-out and due-task digest support.", "Ensure at least one parent context or allow explicitly standalone tasks."],
    security: ["Organization members read tasks; editors create/update; comments retain authorship; viewers optionally comment only if product policy allows."],
    analytics: ["Open/overdue counts, completion time, tasks by owner, and task-to-booked correlation."],
    edgeCases: ["Assignee removed from organization.", "Parent prospect deleted.", "Due dates across timezones.", "Reopened completed tasks."],
    testing: ["RLS and role matrix.", "Notification creation.", "Cascade/set-null rules and concurrent completion."],
    dependencies: ["Organization members, prospects, campaigns, notifications, activity log."],
    risks: ["Feature can expand into full project management; keep scope tied to revenue workflow."],
    rollout: ["Tasks and assignments first.", "Comments second.", "Recurring tasks only after demonstrated demand."],
    acceptanceCriteria: ["Tasks can be connected to prospects and campaigns.", "Assignees receive and can resolve work.", "Overdue tasks appear in daily workflow.", "Task history identifies who changed what."],
  }),
  local({
    key: "custom_prospect_fields", order: 6, phase: 1, title: "True custom prospect fields", tagline: "Let each organization model the qualification data that matters to it.", effort: "Medium–large", value: "High", estimatedDelivery: "2–3 weeks",
    problem: "Configurable industries and platforms are not true custom fields. Agencies need organization-specific data such as budget, employee count, decision maker, current provider, or contract renewal date.",
    outcome: "Admins define typed fields that render consistently in prospect forms, filters, imports, exports, detail views, and later automation rules.",
    workflows: ["Admin creates a field, selects type, label, help text, required/default behavior, and options.", "Members enter values when creating or editing prospects.", "Admin reorders, archives, or safely deletes a definition after reviewing affected values."],
    existingIntegration: ["Extend ProspectForm, detail panel, CSV mapper/export, saved views, and ingestion mappings.", "Expose field values to AI prompt context only when explicitly enabled."],
    userInterface: ["Custom fields builder in Settings.", "Dynamic form section grouped by admin-defined categories.", "Typed filter controls and CSV mapping destinations."],
    dataModel: ["custom_field_definitions with type, options JSON, validation JSON, ordering, archived flag, and organization scope.", "custom_field_values with prospect, definition, typed JSON value; alternatively a validated JSONB prospect column. A normalized value table is preferred for filtering and constraints."],
    backend: ["Central field-definition and value validation service.", "Bulk value loading to prevent N+1 queries.", "Migration tools for option renames and field-type changes."],
    security: ["Admins manage definitions; editors manage values; all queries enforce organization ownership through both definition and prospect."],
    analytics: ["Field completeness and optional aggregation for numeric/select fields."],
    edgeCases: ["Definition archived with existing values.", "Changing field type after data exists.", "Required fields on older prospects.", "Option deletion and CSV invalid values."],
    testing: ["Every field type and validation rule.", "Cross-organization definition/value attacks.", "Import/export fidelity and filter performance."],
    dependencies: ["Prospect CRUD, CSV import/export, filters."],
    risks: ["Unindexed JSON filtering becomes slow; design query strategy before choosing storage."],
    rollout: ["Text, number, date, boolean, and single select.", "Add currency, multi-select, and URL.", "Add automation and reporting support."],
    acceptanceCriteria: ["Admins can define and reorder typed fields.", "Values validate identically on all write paths.", "Fields participate in import, export, and filters.", "Archived definitions preserve historical data."],
  }),
  local({
    key: "import_history_rollback", order: 7, phase: 1, title: "Import history and rollback", tagline: "Make bulk imports traceable, repeatable, and recoverable.", effort: "Medium", value: "High", estimatedDelivery: "1–2 weeks",
    problem: "CSV import creates prospects but does not provide a durable ledger, reusable mapping, or safe way to undo an incorrect batch.",
    outcome: "Every import has an immutable record of source file metadata, mapping, results, errors, and affected rows, with guarded rollback of records created by that import.",
    workflows: ["Upload, map, preview validation, and confirm import.", "Inspect imported, updated, skipped, duplicate, and failed rows later.", "Admin rolls back only rows created by the batch after reviewing downstream changes that would also be affected."],
    existingIntegration: ["Wrap current CSV parser/import action.", "Connect imported prospects to campaigns, tags, assignments, and future deduplication.", "Record import in organization activity."],
    userInterface: ["Import history page or Settings section.", "Batch detail with mapping, result counts, row errors, and download-error CSV.", "Two-step rollback confirmation showing affected messages/tasks/deals."],
    dataModel: ["import_batches, import_rows, and saved_import_mappings.", "Store file name, hash, size, uploader, mapping JSON, status, counts, and timestamps; do not retain raw files by default."],
    backend: ["Process bounded chunks and update batch counters safely.", "Rollback service deletes only batch-created prospects that pass policy and relationship checks.", "Idempotency based on file hash is advisory, not an automatic block."],
    security: ["Organization-scoped batches; admin-only rollback; redact row errors that may expose sensitive source data."],
    analytics: ["Import volume, failure rate, duplicate rate, and time to process."],
    edgeCases: ["Partial chunk failure.", "Prospect modified after import.", "Rollback after outreach or deal creation.", "Same file imported twice intentionally."],
    testing: ["Chunk failure recovery.", "Rollback relationship safety.", "Large files at configured row/size limits."],
    dependencies: ["Current CSV import, prospect creation, campaigns."],
    risks: ["Blind rollback can destroy work completed after import; require impact review and block unsafe deletion by default."],
    rollout: ["Ledger and error history.", "Saved mappings.", "Guarded rollback after dependency analysis."],
    acceptanceCriteria: ["Every import has a durable outcome.", "Users can download row errors.", "Mappings can be reused.", "Rollback never silently removes downstream work."],
  }),
  local({
    key: "deals_revenue_tracking", order: 8, phase: 1, title: "Deals and revenue tracking", tagline: "Connect outreach activity to commercial outcomes and forecast value.", effort: "Medium–large", value: "Very high", estimatedDelivery: "2–4 weeks",
    problem: "Prospect statuses measure outreach progress but cannot represent multiple opportunities, deal value, probability, close dates, products, or won/lost revenue.",
    outcome: "Qualified prospects create deals that move through a commercial pipeline and provide weighted forecast and realized revenue reporting.",
    workflows: ["Create a deal from a replied or booked prospect with value, currency, service, owner, probability, and expected close date.", "Move the deal through configurable stages, record proposal/negotiation milestones, and mark won or lost with required reason.", "Managers review forecast by month, campaign, source, and owner."],
    existingIntegration: ["Prospect and campaign relationships, team assignments, activity log, analytics, notifications, custom fields, and client reporting.", "Prospect status should not be forced to mirror deal stage when multiple deals exist."],
    userInterface: ["Deals pipeline and list views.", "Deal section in prospect detail.", "Forecast cards, stage history, close form, and lost-reason analytics."],
    dataModel: ["deals, deal_stages, deal_stage_history, and optional deal_line_items.", "Store monetary values as integer minor units with ISO currency.", "Support one prospect to many deals and configurable organization stages."],
    backend: ["Transactional stage movement and close actions.", "Weighted forecast calculation using probability with documented currency behavior.", "Do not sum different currencies without conversion or explicit grouping."],
    security: ["Organization RLS; optional deal visibility policy later; editors mutate and viewers read."],
    analytics: ["Pipeline value, weighted forecast, won revenue, average deal size, win rate, sales cycle, and revenue by source/campaign/owner."],
    edgeCases: ["Multiple currencies.", "Reopening won/lost deals.", "Prospect deletion with financial history.", "Value or probability changed after forecast snapshot."],
    testing: ["Money precision and currency grouping.", "Stage-history integrity.", "Forecast filters and close/reopen audit."],
    dependencies: ["Prospects, campaigns, team members, activity log; custom fields are complementary."],
    risks: ["Revenue reporting loses credibility if currencies and stage history are handled casually."],
    rollout: ["Fixed default stages and single-value deals.", "Configurable stages and line items.", "Forecast snapshots and client reporting."],
    acceptanceCriteria: ["Users can manage multiple deals per prospect.", "Won/lost decisions are auditable.", "Forecast never mixes currencies invisibly.", "Revenue traces back to source, campaign, and owner."],
  }),
  local({
    key: "lead_source_attribution", order: 9, phase: 1, title: "Lead-source attribution", tagline: "Preserve where every prospect came from and which source produces revenue.", effort: "Medium", value: "Very high", estimatedDelivery: "2–3 weeks",
    problem: "A single informal source field cannot preserve original versus latest attribution or report campaign, ad, form, referral, and UTM performance.",
    outcome: "Prospects carry immutable original attribution plus a history of subsequent acquisition touches connected to conversion and revenue reporting.",
    workflows: ["Capture attribution during manual entry, CSV import, webhook ingestion, or hosted form submission.", "Review original and latest source in prospect detail.", "Analyze leads, replies, bookings, deals, and revenue by source hierarchy."],
    existingIntegration: ["Prospect creation/import, campaigns, deals, analytics, custom fields, and future ingestion adapters."],
    userInterface: ["Attribution section in prospect detail and creation/import mapping.", "Source manager in Settings and source/campaign reporting dashboard."],
    dataModel: ["lead_sources plus prospect_attributions with provider, source, campaign, ad set, ad, form, landing page, referrer, UTMs, captured_at, and original/latest flags.", "Preserve provider external IDs and raw display names separately."],
    backend: ["Central attribution service used by every prospect creation path.", "Deterministic original/latest rules and idempotency for repeated events.", "Backfill existing prospects with unknown/manual attribution."],
    security: ["Organization-scoped source configuration and attribution; do not expose provider credentials in attribution records."],
    analytics: ["Lead volume, positive replies, bookings, win rate, revenue, CPL when spend is supplied, and cost per booked meeting."],
    edgeCases: ["Conflicting UTMs.", "Prospect merged across sources.", "Source renamed or deleted.", "Multiple touches at identical timestamps."],
    testing: ["Original attribution immutability.", "Latest-attribution ordering.", "Merge behavior and aggregate correctness."],
    dependencies: ["Prospects and campaigns; deals unlock revenue attribution."],
    risks: ["Attribution models can become contentious; start with clearly defined original and latest touch instead of claiming multi-touch causality."],
    rollout: ["Manual/import attribution.", "Analytics.", "Automatic capture through inbound integrations."],
    acceptanceCriteria: ["Every new prospect has a source classification.", "Original source cannot be silently overwritten.", "Latest source is deterministic.", "Conversion and revenue reports drill down to source."],
  }),
  local({
    key: "lead_scoring", order: 10, phase: 1, title: "Transparent lead scoring", tagline: "Prioritize prospects using explainable organization-defined criteria.", effort: "Medium", value: "High", estimatedDelivery: "2–3 weeks",
    problem: "Large lists offer no consistent way to identify best-fit or most-engaged prospects, while opaque AI scores undermine trust.",
    outcome: "Each prospect receives a score and visible explanation based on configurable fit, activity, source, recency, and intent rules.",
    workflows: ["Admin creates weighted rules and previews their effect on existing prospects.", "Users see score, band, and contributing reasons in lists and detail.", "Scores recalculate when relevant data changes and can trigger saved views or automation."],
    existingIntegration: ["Custom fields, attribution, replies, call outcomes, messages, deals, saved views, and automation rules."],
    userInterface: ["Scoring configuration with rule simulator.", "Score badge and explanation popover.", "Score distribution and conversion-by-band analytics."],
    dataModel: ["lead_score_models, lead_score_rules, and prospect_score_snapshots or current score columns plus calculation timestamp/version.", "Rules reference only allowlisted fields and operators."],
    backend: ["Pure deterministic scoring engine with versioned models.", "Recalculate synchronously for individual changes and in batches after model edits.", "Store reason breakdown for auditability."],
    security: ["Admins configure models; all members view explanations; organization boundaries apply to referenced fields."],
    analytics: ["Conversion by score band, score calibration, and distribution drift."],
    edgeCases: ["Missing field values.", "Archived custom fields.", "Model changes while batch recalculation runs.", "Scores outside configured range."],
    testing: ["Deterministic rule evaluation.", "Model versioning and batch recalculation.", "Authorization and performance at large prospect counts."],
    dependencies: ["Useful immediately with core fields; substantially stronger after custom fields, attribution, and reply outcomes."],
    risks: ["Bad rules can encode bias or prioritize vanity engagement; expose every contribution and measure calibration."],
    rollout: ["Fixed system rules.", "Admin-defined weights.", "Automation triggers after scoring reliability is proven."],
    acceptanceCriteria: ["Every score is explainable.", "Model changes are versioned.", "Recalculation is reliable and observable.", "Score bands correlate with measurable outcomes or are flagged for adjustment."],
  }),
  local({
    key: "usage_metering_plan_limits", order: 11, phase: 1, title: "Usage metering and plan limits", tagline: "Measure billable activity before introducing subscriptions.", effort: "Medium", value: "High", estimatedDelivery: "1–2 weeks",
    problem: "Commercial plans cannot be enforced or priced responsibly without trusted usage measurements for seats, prospects, imports, AI generations, sequences, integrations, and storage.",
    outcome: "ReachFlow records auditable usage, displays current consumption, and enforces documented limits without relying on payment-provider data.",
    workflows: ["Admin views usage against plan allowances and receives warnings before limits.", "A bounded action checks entitlement before creating billable resources.", "Support can inspect usage events and apply a time-limited override with audit history."],
    existingIntegration: ["Organizations.plan, members, prospects, imports, generation_logs, sequences, and future integrations/billing."],
    userInterface: ["Usage section in Settings with meters and reset dates.", "Clear limit-reached messages and upgrade placeholders.", "Internal override controls restricted to roadmap-authorized or future support roles."],
    dataModel: ["plan_entitlements, usage_counters, append-only usage_events, and entitlement_overrides.", "Define metric unit, period, hard/soft limit, and idempotency key."],
    backend: ["Central entitlement service called server-side before mutations.", "Atomic increments or derived counts depending on metric.", "Scheduled reconciliation detects counter drift."],
    security: ["Customers read only their organization usage; only trusted server paths write events; never accept client-supplied quantities blindly."],
    analytics: ["Consumption distribution, limit-hit rate, upgrade intent, and reconciliation drift."],
    edgeCases: ["Concurrent requests at limit boundary.", "Downgrade below current usage.", "Refunded/deleted resources.", "Clock and billing-period boundaries."],
    testing: ["Atomic concurrency tests.", "Period rollover and override expiry.", "Reconciliation against source tables."],
    dependencies: ["Existing organization plan field and measurable source tables; required foundation for Pesapal billing."],
    risks: ["Incorrect counters create billing disputes; use idempotent events and reconciliation."],
    rollout: ["Measure without enforcement.", "Show warnings.", "Enable hard limits only after reconciliation proves accurate."],
    acceptanceCriteria: ["Every billable metric has an owner and definition.", "Usage is reproducible from source data or events.", "Concurrent requests cannot exceed hard limits silently.", "Customers can see why an action was blocked."],
  }),
  local({
    key: "data_retention_consent", order: 12, phase: 1, title: "Data retention, consent, and suppression controls", tagline: "Make contact restrictions durable across every import and outreach path.", effort: "Medium", value: "High", estimatedDelivery: "2–3 weeks",
    problem: "A deleted prospect or note is not a reliable do-not-contact mechanism. Agencies need durable suppression, consent provenance, retention, export, and deletion workflows for personal data.",
    outcome: "ReachFlow prevents prohibited outreach, records why contact is allowed or blocked, and supports traceable data-subject export and deletion operations.",
    workflows: ["Mark a prospect do-not-contact with reason, source, and timestamp; every send/enrollment/import path respects the suppression identity.", "Admin configures organization retention periods and previews records eligible for archive or deletion.", "Process a data export or deletion request with a review step and immutable operational audit."],
    existingIntegration: ["Prospect identities, phone/email normalization, imports, sequences, outreach composer, activity log, and future connected channels."],
    userInterface: ["Compliance section in prospect detail and Settings.", "Suppression-list search/import/export and retention review queue.", "Clear blocked-action explanations without exposing sensitive suppression details broadly."],
    dataModel: ["suppression_entries keyed by normalized identity and organization, consent_records, privacy_requests, and retention_policies.", "Keep minimal suppression evidence even when prospect content is deleted, subject to legal review."],
    backend: ["Central canContact guard used by all manual and automated outreach paths.", "Background retention preview/execution jobs with dry-run reports.", "Portable prospect data export service."],
    security: ["Admin-only policy configuration and privacy requests; tightly limit exported data URLs and expire them.", "Never place sensitive export files in public storage."],
    analytics: ["Suppression rate, blocked attempts, privacy-request aging, and records approaching retention limits."],
    edgeCases: ["Same identity on multiple prospects.", "Suppression imported before prospect exists.", "Legal hold overriding retention.", "Re-consent after previous opt-out."],
    testing: ["Every outreach path must fail closed for suppressed identities.", "Export completeness and cross-tenant isolation.", "Retention dry-run and legal-hold behavior."],
    dependencies: ["Normalized phone/email identities; duplicate management improves reliability."],
    risks: ["Legal requirements vary by jurisdiction; product controls need review by qualified counsel before compliance claims."],
    rollout: ["Do-not-contact and suppression first.", "Consent provenance and privacy requests.", "Automated retention only after dry-run validation."],
    acceptanceCriteria: ["Suppressed identities cannot receive manual or automated outreach.", "Consent and suppression changes are auditable.", "Exports contain all organization-held prospect data.", "Retention never deletes legal-hold records."],
  }),
  local({
    key: "duplicate_detection_merging", order: 13, phase: 1, title: "Duplicate detection and prospect merging", tagline: "Keep one reliable customer story as data arrives from more sources.", effort: "Medium–large", value: "High", estimatedDelivery: "2–4 weeks",
    problem: "Manual entry, CSV imports, and future integrations will create duplicates unless ReachFlow normalizes identities, detects conflicts, and provides a safe merge process.",
    outcome: "Potential duplicates are scored and reviewed; confirmed merges preserve the canonical prospect plus messages, tasks, deals, campaigns, tags, attribution, and audit history.",
    workflows: ["System flags exact email/phone/provider-ID matches and suggests fuzzy business/location matches.", "Reviewer compares records field by field, selects surviving values, previews relationships, and confirms merge.", "Creation/import paths warn or enrich an existing prospect according to confidence and configured policy."],
    existingIntegration: ["Prospects, phone/email/handles, tags, campaigns, messages, sequences, tasks, deals, attribution, and imports."],
    userInterface: ["Duplicate review queue and side-by-side merge screen.", "Creation warning with open-existing and create-anyway options for non-exact matches.", "Merged-record activity entry linking former identifiers."],
    dataModel: ["prospect_identities with normalized type/value and organization-scoped uniqueness; duplicate_candidates; prospect_merge_log with source, target, field decisions, and relationship counts."],
    backend: ["Normalization service and confidence rules.", "Transactional merge service locking both records and moving every dependent relationship safely.", "Idempotent handling for concurrent ingestion events."],
    security: ["Only organization editors/admins review; restrict final merges to admins initially.", "Never compare identities across organizations."],
    analytics: ["Duplicate suggestion rate, confirmed/false-positive rate, and duplicates prevented by source."],
    edgeCases: ["Both records have active sequences or open deals.", "Conflicting suppression/consent—most restrictive wins.", "Unique campaign/tag relationships and simultaneous edits."],
    testing: ["Transaction rollback for every dependent table.", "Normalization across countries and casing.", "Concurrency, RLS, and merge-audit completeness."],
    dependencies: ["Benefits from custom fields, attribution, tasks, and deals being defined before relationship migration logic."],
    risks: ["A partial merge can corrupt history; inventory every foreign key and test the operation as a single transaction."],
    rollout: ["Exact-match warnings.", "Review queue and manual merge.", "Source-specific automatic enrichment only after false-positive measurement."],
    acceptanceCriteria: ["Exact identities cannot silently belong to two prospects in one organization.", "Merges preserve all supported relationships.", "Consent conflicts fail safely.", "Every merge is auditable."],
  }),
  local({
    key: "automation_rules", order: 14, phase: 1, title: "Automation rules", tagline: "Automate repeatable CRM operations with constrained, auditable rules.", effort: "Large", value: "Very high", estimatedDelivery: "4–8 weeks",
    problem: "Sequences automate timed outreach only. Teams still manually assign, tag, schedule, notify, and route prospects after common events.",
    outcome: "Admins configure event-condition-action rules using a bounded vocabulary, with execution logs, idempotency, retries, and loop prevention.",
    workflows: ["Choose trigger, add AND/OR conditions, configure ordered actions, test against sample prospects, then activate.", "Inspect every execution, skipped condition, action result, and failure; retry safe failures manually.", "Pause a rule immediately and version changes rather than mutating active definitions invisibly."],
    existingIntegration: ["Prospect/status mutations, tags, assignments, follow-ups, tasks, sequences, notifications, lead scores, deals, and outgoing webhooks."],
    userInterface: ["Rule builder in Settings with plain-language summary.", "Test mode, version history, execution log, failure details, and pause switch."],
    dataModel: ["automation_rules, rule_versions, automation_executions, and action_attempts with idempotency keys.", "Store constrained JSON definitions validated by versioned Zod schemas."],
    backend: ["Publish domain events after successful mutations.", "Background worker evaluates conditions and performs allowlisted actions.", "Depth limits, causation IDs, and cooldowns prevent recursive loops."],
    security: ["Admin-only rule management; execution uses organization context and never service-role access without explicit row ownership checks."],
    analytics: ["Executions, success/failure, time saved estimate, actions by rule, and conversion influenced—not falsely attributed—by automation."],
    edgeCases: ["Rule edits during execution.", "Deleted referenced tags/users/sequences.", "Two rules writing the same field.", "Retries of non-idempotent actions."],
    testing: ["Schema validation and condition engine matrix.", "Loop prevention, idempotency, retry, concurrency, and tenant isolation.", "Simulation must never mutate data."],
    dependencies: ["Tasks, saved views/filter semantics, scoring, and stable mutation domain events."],
    risks: ["A generic workflow engine is an unbounded product; start with a short approved trigger/action list."],
    rollout: ["Five triggers and five local actions.", "Execution observability and retries.", "External webhook actions after delivery infrastructure exists."],
    acceptanceCriteria: ["Rules have versioned definitions and readable summaries.", "Every execution is explainable and idempotent.", "Recursive rules cannot run indefinitely.", "Failures are visible and safely retryable."],
  }),
  local({
    key: "client_reporting_portal", order: 15, phase: 2, title: "Client reporting portal", tagline: "Give agency clients a secure, branded view of campaign progress.", effort: "Medium–large", value: "Very high", estimatedDelivery: "3–5 weeks",
    problem: "Agencies repeatedly build status reports and answer client questions manually, while full CRM access exposes internal or unrelated data.",
    outcome: "Admins publish narrowly scoped read-only portals showing approved campaigns, metrics, and selected prospect fields under agency branding.",
    workflows: ["Admin creates a portal, selects campaigns/date range/visible metrics, previews as client, sets expiry and optional passcode, then shares link.", "Client views current performance and downloads an approved report without a ReachFlow account.", "Admin revokes or rotates access and reviews last access."],
    existingIntegration: ["Campaigns, prospects, deals, attribution, analytics, white-label settings, organization logo/colors."],
    userInterface: ["Portal manager inside Campaigns or Settings.", "Public /report/[token] route with branded overview, funnel, activity trend, and sanitized prospect table."],
    dataModel: ["client_portals, portal_campaigns, portal_access_events, token hash, expiry, revoked timestamp, and visibility configuration."],
    backend: ["Server-only token resolution using hashed high-entropy tokens.", "Security-invoker queries or narrowly scoped functions that cannot reveal other organization data.", "Optional PDF/CSV generation as a later enhancement."],
    security: ["Never use predictable IDs as access tokens.", "Rate limit public access, redact internal notes/contact details by default, and support immediate revocation."],
    analytics: ["Portal visits and report freshness plus the approved campaign KPIs; avoid invasive client tracking."],
    edgeCases: ["Expired/revoked token.", "Campaign removed after sharing.", "White-label assets missing.", "No data in selected period."],
    testing: ["Token entropy/revocation and cross-tenant leakage.", "Every visibility toggle.", "Public caching and stale-data behavior."],
    dependencies: ["Campaign analytics; deals and attribution make the portal materially stronger."],
    risks: ["A single exposed internal field is a serious privacy incident; use explicit allowlists, never select * for portal payloads."],
    rollout: ["Authenticated preview and share token.", "Branding and export.", "Optional client accounts/comments only after demand."],
    acceptanceCriteria: ["Portal reveals only configured campaigns and fields.", "Tokens expire and revoke immediately.", "Client metrics match internal reports.", "No login is required for intentionally shared links."],
  }),
  local({
    key: "webhook_delivery_center", order: 16, phase: 2, title: "Webhook delivery center", tagline: "Provide the reliability layer required before connecting customer systems.", effort: "Medium", value: "High", estimatedDelivery: "2–3 weeks",
    problem: "External delivery cannot be trusted without visibility into destination health, attempts, responses, retry schedule, and dead-letter failures.",
    outcome: "Admins can inspect and safely retry every outbound webhook delivery while secrets and sensitive payloads remain protected.",
    workflows: ["Open delivery center, filter failures, inspect redacted request/response metadata, and retry eligible events.", "Disable an unhealthy endpoint automatically after configured failure thresholds and notify admins.", "Rotate signing secret without losing verification during a short overlap window."],
    existingIntegration: ["Notifications, activity log, future automation rules, and outgoing integration webhooks."],
    userInterface: ["Endpoint health list, delivery ledger, attempt detail, retry button, and secret rotation controls."],
    dataModel: ["webhook_endpoints, webhook_events, webhook_deliveries, and delivery_attempts with status, response code, bounded response excerpt, timing, and next retry."],
    backend: ["Background queue/worker with exponential bounded backoff, jitter, timeout, and idempotent event IDs.", "HMAC signing over timestamp and raw body.", "SSRF protections: HTTPS, DNS/IP validation, redirect restrictions, and request size limits."],
    security: ["Encrypt endpoint secrets or store in a secrets service; never return them after creation.", "Redact authorization headers and sensitive payload values."],
    analytics: ["Endpoint success rate, latency, retry count, disabled endpoints, and oldest failed event."],
    edgeCases: ["DNS rebinding and private IP destinations.", "Endpoint returns huge body or redirect.", "Retry after endpoint rotation.", "Duplicate delivery acknowledgment."],
    testing: ["Signature fixtures customers can verify.", "SSRF and redirect tests.", "Backoff, timeout, retry, and dead-letter behavior."],
    dependencies: ["Background job infrastructure; should precede customer-facing outgoing webhooks."],
    risks: ["Webhook delivery is a security boundary; SSRF and secret leakage require deliberate hardening."],
    rollout: ["Internal delivery ledger.", "Customer health UI and retries.", "Endpoint auto-disable and secret rotation."],
    acceptanceCriteria: ["Every event has a visible terminal or retrying state.", "Requests are signed and bounded.", "Unsafe destinations are rejected.", "Admins can diagnose failures without database access."],
  }),
  {
    key: "outgoing_automation_webhooks", order: 17, phase: 2, title: "Outgoing Zapier, Make, and n8n webhooks", tagline: "Notify external automation tools when meaningful CRM events occur.", effort: "Medium", value: "High", estimatedDelivery: "2–3 weeks",
    problem: "Customers cannot connect ReachFlow outcomes to their existing operational systems without polling or manual exports.",
    outcome: "Organization endpoints subscribe to versioned events such as prospect.created, prospect.status_changed, reply.recorded, meeting.booked, deal.won, and task.completed.",
    workflows: ["Admin creates endpoint, selects events, receives a one-time signing secret, sends a test event, and activates it.", "External system verifies HMAC signature, processes event idempotently, and returns 2xx.", "Admin monitors delivery center and rotates/revokes endpoint."],
    existingIntegration: ["Domain events from prospects, replies, tasks, deals, attribution, and automation rules; all delivery uses the delivery center."],
    userInterface: ["Integration settings with endpoint form, event picker, sample payload, signature guide, test action, and health status."],
    dataModel: ["Reuse webhook endpoint/delivery tables; add endpoint event subscriptions and payload schema version."],
    backend: ["Outbox pattern commits events alongside domain mutations.", "Publisher converts internal event to documented public payload and queues delivery.", "Maintain backward-compatible schema versions."],
    security: ["HMAC-SHA256 signature, timestamp tolerance, secret rotation, SSRF protection, and explicit payload allowlists."],
    analytics: ["Events generated/delivered by type and endpoint health."],
    edgeCases: ["Transaction succeeds but queue publication fails—outbox worker recovers.", "Endpoint subscribes after event creation.", "Payload references subsequently deleted prospect."],
    testing: ["Outbox atomicity.", "Signature examples against multiple languages.", "Schema-version contract tests."],
    dependencies: ["Webhook delivery center and stable domain event definitions."],
    risks: ["Changing payloads breaks customer automations; version contracts from first release."],
    rollout: ["Generic webhook endpoint and six events.", "Publish Zapier/Make/n8n setup recipes.", "Native marketplace apps only after usage validates demand."],
    acceptanceCriteria: ["Committed domain events cannot be silently lost.", "Customers can verify signatures using documentation fixtures.", "Payloads contain only documented organization data.", "Failed deliveries are observable and retryable."],
    externalRequirements: [{ service: "Customer-owned Zapier, Make, n8n, or HTTPS endpoint", purpose: "Receive ReachFlow event payloads.", setup: ["Customer creates a webhook trigger or HTTPS receiver.", "Customer stores the ReachFlow signing secret and implements idempotency using event_id."], credentials: ["No provider API key is required for generic webhooks.", "ReachFlow generates a per-endpoint HMAC signing secret."], webhooks: ["ReachFlow sends HTTPS POST requests; destination must acknowledge with 2xx."] }],
  },
  {
    key: "lead_ingestion_foundation", order: 18, phase: 3, title: "Lead ingestion foundation and generic inbound webhook", tagline: "Accept, normalize, deduplicate, attribute, and route leads from external systems.", effort: "Large", value: "Very high", estimatedDelivery: "5–8 weeks",
    problem: "Prospects currently depend on manual entry or CSV import. Reliable automatic intake requires authentication, idempotency, normalization, mapping, duplicate handling, routing, and failure review.",
    outcome: "Each organization can create an authenticated inbound source and submit leads to a documented contract that creates or enriches exactly one prospect with visible processing outcome.",
    workflows: ["Admin creates source, receives endpoint URL and secret, configures field mappings/defaults/routing, and sends test payload.", "Provider event is authenticated, stored in immutable ledger, acknowledged quickly, and processed asynchronously.", "Failed events show validation or processing error and support safe replay after correction."],
    existingIntegration: ["Prospect creation, identities, deduplication, attribution, assignments, tags, campaigns, sequences, activity log, and notifications."],
    userInterface: ["Lead Sources settings, mapping editor, test console, health status, event ledger, failed-event detail, and replay action."],
    dataModel: ["lead_sources, ingestion_events, source_field_mappings, routing_rules, and prospect_identities/attributions.", "Unique organization/source/external_event_id enforces idempotency."],
    backend: ["Thin authenticated route validates size/signature and persists before responding 2xx.", "Background processor normalizes, maps, matches, creates/enriches, attributes, routes, and records terminal outcome.", "Bounded retries and dead-letter review."],
    security: ["Per-source secret hashing/rotation, HMAC timestamp/replay checks, payload limits, rate limits, and redacted retention policy.", "Never expose raw payloads to unauthorized roles."],
    analytics: ["Capture success, duplicate/enrichment rate, processing latency, failure reason, source health, and automatic assignment rate."],
    edgeCases: ["Provider retries and out-of-order events.", "Conflicting fields on existing prospect.", "Secret rotation overlap.", "Mapping changed while event waits."],
    testing: ["Signature and replay attacks.", "Idempotent concurrency.", "Mapping versions, matching confidence, routing, retries, and tenant isolation."],
    dependencies: ["Attribution, duplicate identities/merge policy, and delivery/processing observability."],
    risks: ["Silent lead loss or duplication destroys trust; immutable event ledger and idempotency are non-negotiable."],
    rollout: ["Normalized contract and ledger.", "Generic HMAC webhook with mappings.", "Routing/enrichment and integration recipes."],
    acceptanceCriteria: ["One valid external event produces one visible outcome.", "Retries cannot duplicate prospects.", "Admins can diagnose every failure.", "Routing and attribution are deterministic and auditable."],
    externalRequirements: [{ service: "Customer automation or source system", purpose: "POST lead payloads to ReachFlow.", setup: ["Create a ReachFlow lead source.", "Configure HTTPS POST with JSON payload and timestamp/signature headers.", "Map source fields and test with a non-production record."], credentials: ["ReachFlow-generated source ID and signing secret."], webhooks: ["Inbound endpoint such as /api/ingest/v1/{sourceId}; exact contract documented and versioned."] }],
  },
  {
    key: "forms_native_lead_sources", order: 19, phase: 3, title: "Website forms and native lead-source ingestion", tagline: "Capture leads from forms and validated advertising providers without manual transfer.", effort: "Large", value: "Very high", estimatedDelivery: "6–12 weeks after ingestion foundation",
    problem: "Generic webhooks unlock technical customers but agencies also need simple forms and native sources such as Meta Lead Ads with provider-specific authorization and field handling.",
    outcome: "ReachFlow offers hosted/embeddable forms plus one demand-validated native adapter, provisionally Meta Lead Ads, all using the shared ingestion pipeline.",
    workflows: ["Build form, select fields and consent text, configure thank-you behavior and routing, then embed or share hosted URL.", "For Meta, admin authorizes account, selects Page/forms, maps fields, subscribes, and monitors connection health.", "Incoming submission enters the same event ledger and deduplication/attribution workflow."],
    existingIntegration: ["Lead ingestion foundation, custom fields, attribution, routing, suppression/consent, campaigns, and sequences."],
    userInterface: ["Form builder and submissions view.", "Connections wizard with provider account/page/form selectors, mapping, test, sync status, and reconnect controls."],
    dataModel: ["hosted_forms, form_fields, form_submissions, provider_connections, provider_resources, encrypted credential references, token expiry, and last health check."],
    backend: ["Public form endpoint with anti-spam controls.", "Provider OAuth callback, webhook verification, subscription management, token refresh, backfill where supported, and adapter-to-normalized-contract translation."],
    security: ["CSRF/spam/rate limiting for forms; consent capture and origin controls.", "Encrypt provider tokens, minimize scopes, verify webhook signatures, and isolate credentials by organization."],
    analytics: ["Form views/submissions/conversion, source health, lead volume, and downstream conversion by form/ad."],
    edgeCases: ["Provider permissions revoked.", "Form deleted while webhook events arrive.", "Token expiry and page ownership changes.", "Spam and duplicate submissions."],
    testing: ["Public-form abuse tests.", "OAuth state validation and token refresh.", "Provider webhook fixtures, retries, field mapping, and reconnection."],
    dependencies: ["Lead ingestion, attribution, deduplication, consent controls, and provider demand validation."],
    risks: ["Native adapters require ongoing maintenance and provider review; launch one provider only after customer interviews."],
    rollout: ["Hosted forms.", "Embeddable forms.", "One native source selected by demonstrated demand."],
    acceptanceCriteria: ["Forms capture consent and route reliably.", "Provider connection health is visible.", "Revoked permissions fail visibly.", "All submissions share the same idempotent ingestion contract."],
    externalRequirements: [{ service: "Meta for Developers (provisional native source)", purpose: "Receive Meta Lead Ads submissions.", setup: ["Create Meta Business app and configure OAuth redirect domains.", "Complete required business verification/app review for production permissions.", "Connect Pages and subscribe the app to leadgen webhooks."], credentials: ["META_APP_ID", "META_APP_SECRET", "META_WEBHOOK_VERIFY_TOKEN", "META_APP_ACCESS_TOKEN where required"], webhooks: ["Public HTTPS callback for Meta verification and leadgen notifications.", "Verify X-Hub-Signature-256 and retrieve lead details using approved Graph API permissions."] }],
  },
  {
    key: "calendar_integration", order: 20, phase: 3, title: "Calendar integration", tagline: "Connect booked meetings to prospects and automate meeting outcomes.", effort: "Medium–large", value: "High", estimatedDelivery: "3–6 weeks",
    problem: "Booked status and follow-up dates are disconnected from actual calendars, creating duplicate entry and weak visibility into attendance, cancellation, and no-shows.",
    outcome: "Users connect Google Calendar first, associate events with prospects, create meetings, and synchronize lifecycle changes safely.",
    workflows: ["User authorizes calendar with minimum scopes and selects default calendar.", "Create meeting from prospect, invite attendees, and store provider event link.", "Webhook/polling sync updates scheduled, cancelled, completed, or no-show status and creates reminders/tasks."],
    existingIntegration: ["Prospect booked status, follow-ups, tasks, notifications, deals, and analytics."],
    userInterface: ["Calendar connection settings, upcoming meeting list, meeting form in prospect detail, conflict warning, and disconnect controls."],
    dataModel: ["calendar_connections, calendars, prospect_meetings, provider_event_id/version, sync token, status, attendees, starts/ends/timezone."],
    backend: ["OAuth authorization/callback and encrypted refresh tokens.", "Incremental sync and push notification renewal where supported.", "Conflict/idempotency rules for local versus provider edits."],
    security: ["Minimum scopes, encrypted tokens, OAuth state/PKCE, revocation, and no broad event-content storage beyond needed fields."],
    analytics: ["Meetings booked, attended, cancelled, no-show, booking-to-win conversion, and owner performance."],
    edgeCases: ["Recurring events.", "Organizer changes.", "Timezone/DST.", "Disconnected account and expired notification channels."],
    testing: ["OAuth callback/state.", "Sync conflicts, recurrence, cancellation, timezone, and token refresh fixtures."],
    dependencies: ["Tasks and deals improve meeting follow-through; core can ship with prospects and notifications."],
    risks: ["Bidirectional sync can overwrite user changes; define source-of-truth rules and expose conflicts."],
    rollout: ["Google Calendar create/link.", "Incremental updates and outcomes.", "Microsoft Graph only after demand."],
    acceptanceCriteria: ["Meetings link reliably to prospects.", "Cancellation and time changes synchronize idempotently.", "Disconnect revokes access and stops sync.", "Timezone behavior is correct."],
    externalRequirements: [{ service: "Google Cloud / Google Calendar API", purpose: "OAuth connection and calendar event synchronization.", setup: ["Create Google Cloud project and OAuth consent screen.", "Enable Calendar API and configure authorized redirect URI.", "Complete verification if requested scopes or user scale require it."], credentials: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_CALENDAR_REDIRECT_URI"], webhooks: ["Public HTTPS notification endpoint for Calendar watch channels; renew channels before expiry."] }],
  },
  {
    key: "connected_email", order: 21, phase: 3, title: "Connected email sending, delivery, and reply tracking", tagline: "Move from manually recorded outreach to trustworthy connected email conversations.", effort: "Large", value: "Very high", estimatedDelivery: "8–16 weeks",
    problem: "Marked-as-sent records do not prove delivery and cannot automatically capture bounces, replies, threading, or provider send limits.",
    outcome: "Users connect a mailbox or approved sending provider, send from ReachFlow, and see queued, sent, delivered, bounced, replied, and unsubscribed events in the unified timeline.",
    workflows: ["Connect mailbox, verify sender identity, select signature/defaults, and send a test.", "Compose or approve generated email; worker sends with stable Message-ID and provider idempotency.", "Delivery events and replies update message status, stop sequences, classify reply, and notify assignee."],
    existingIntegration: ["Messages, templates, AI generation, sequences, reply tracking, suppression, analytics, activity log, and notifications."],
    userInterface: ["Mailbox connections, composer send controls, status timeline, bounce/reply detail, sending limits, and reconnect health."],
    dataModel: ["email_connections, outbound_email_jobs, message_delivery_events, email_threads, provider_message IDs, encrypted token references, and suppression updates."],
    backend: ["Provider abstraction, queue, rate limiting, retries, thread headers, MIME parsing, attachment policy, bounce classification, and inbound reply processor.", "Separate transient provider failure from permanent recipient failure."],
    security: ["Encrypt refresh/API tokens, least scopes, malware/size controls for attachments, HTML sanitization, unsubscribe enforcement, and audit access to message content."],
    analytics: ["Sent/delivered/bounced/replied/booked rates, domain health indicators, sequence step performance, and mailbox volume."],
    edgeCases: ["Auto-replies, forwarding, aliases, threading ambiguity, provider quotas, duplicate webhooks, token revocation, and partial MIME content."],
    testing: ["Provider sandbox/fixture contract tests.", "MIME/threading and webhook signature tests.", "Retry/idempotency, suppression, quotas, and cross-tenant isolation."],
    dependencies: ["Reply classification, suppression, usage metering, sequences, and robust background processing."],
    risks: ["Deliverability and provider policy are ongoing operational responsibilities; begin with one sending path and conservative limits."],
    rollout: ["Transactional provider or SMTP send-only pilot.", "Delivery/bounce webhooks.", "Google/Microsoft connected inbox replies after operational reliability."],
    acceptanceCriteria: ["Every send has an observable status.", "Duplicate callbacks do not duplicate timeline events.", "Replies stop sequences correctly.", "Suppression and provider limits are enforced before send."],
    externalRequirements: [{ service: "Initial email provider (choose Resend/Postmark/SendGrid) and later Google Workspace/Microsoft 365", purpose: "Send email, receive delivery events, and optionally synchronize replies.", setup: ["Verify sending domain with SPF/DKIM records.", "Create provider project/API key and configure event webhook.", "For connected inboxes, create Google Cloud and/or Microsoft Entra OAuth applications with reviewed scopes."], credentials: ["EMAIL_PROVIDER_API_KEY", "EMAIL_WEBHOOK_SIGNING_SECRET", "GOOGLE_CLIENT_ID/SECRET and/or MICROSOFT_CLIENT_ID/SECRET when inbox sync is enabled"], webhooks: ["Provider delivery/bounce webhook.", "Inbound email or Gmail/Microsoft change-notification endpoint with signature/token validation."] }],
  },
  {
    key: "pesapal_billing", order: 22, phase: 3, title: "Pesapal billing and subscriptions", tagline: "Accept mobile-money and card payments and enforce commercial plans safely.", effort: "Large", value: "Required for launch", estimatedDelivery: "6–10 weeks including certification",
    problem: "ReachFlow cannot sell recurring access or manage payment state. Uganda-based operations require a provider supporting regional mobile money and global card payments.",
    outcome: "Customers choose a plan, create a Pesapal order, complete hosted payment, receive verified subscription entitlement, and access invoices/payment history with grace-period handling.",
    workflows: ["Admin selects monthly/annual plan and billing identity, then is redirected to Pesapal hosted checkout.", "ReachFlow verifies callback/IPN independently before activating or renewing entitlement.", "Failed/expired payments enter grace period and notify admins; successful renewal restores access without data loss."],
    existingIntegration: ["Organizations.plan, usage metering, entitlements, notifications, email, and settings."],
    userInterface: ["Billing page with plans, usage, checkout, current status, renewal date, transaction history, receipts, and cancellation guidance.", "Internal reconciliation view for mismatched or pending transactions."],
    dataModel: ["billing_customers, subscriptions, billing_orders, payment_transactions, payment_events, invoices/receipts, plan_prices, and entitlement changes.", "Store amounts in minor units and provider references uniquely."],
    backend: ["OAuth/token acquisition according to current Pesapal API, RegisterIPNURL, SubmitOrderRequest, callback page, IPN handler, and GetTransactionStatus reconciliation.", "Never trust browser return parameters as payment confirmation.", "Scheduled reconciliation and idempotent state machine."],
    security: ["Server-only consumer key/secret, verified IPN flow, amount/currency comparison, replay protection, audit log, and no card data stored by ReachFlow."],
    analytics: ["Checkout conversion, successful/failed/pending payments, MRR-equivalent by currency, churn, grace-period recovery, and reconciliation mismatches."],
    edgeCases: ["Delayed/duplicate IPNs.", "Customer closes checkout.", "Currency mismatch.", "Payment succeeds after order expiry.", "Upgrade/downgrade mid-period and mobile-money pending state."],
    testing: ["Pesapal sandbox end-to-end paths.", "Forged callback and duplicate IPN.", "State-machine transitions, entitlement reconciliation, currencies, and grace expiry."],
    dependencies: ["Usage metering and plan entitlements must be trusted before payment activation controls access."],
    risks: ["Payment correctness is high stakes; certification, reconciliation, accounting, tax, refund, and recurring-payment limitations must be validated with Pesapal and advisors."],
    rollout: ["Sandbox and internal transactions.", "One-time plan purchase with manual renewal if recurring support requires it.", "Production certification, monitored launch, then upgrades/downgrades/refunds."],
    acceptanceCriteria: ["Access changes only after server-side payment verification.", "Duplicate notifications are idempotent.", "Every order can be reconciled with Pesapal.", "Failures preserve customer data and show actionable status.", "Secrets never reach client bundles."],
    externalRequirements: [{ service: "Pesapal API 3.0 merchant account", purpose: "Hosted mobile-money/card checkout and payment status notifications.", setup: ["Open and verify Pesapal merchant account.", "Obtain sandbox credentials, register IPN URL, test supported currencies/payment methods, and complete production onboarding/certification.", "Confirm recurring-payment, refund, settlement, tax-receipt, and regional mobile-money behavior with Pesapal before final product promises."], credentials: ["PESAPAL_CONSUMER_KEY", "PESAPAL_CONSUMER_SECRET", "PESAPAL_IPN_ID", "PESAPAL_CALLBACK_URL", "PESAPAL_ENVIRONMENT"], webhooks: ["Public HTTPS IPN endpoint registered through Pesapal.", "Hosted checkout callback for user experience only; transaction status API remains authoritative."] }],
  },
]

export const ROADMAP_FEATURE_KEYS = ROADMAP_FEATURES.map((feature) => feature.key)
