import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocument } from "@/components/legal/legal-document";

export const metadata: Metadata = { title: "Terms of Service | ReachFlow", description: "Terms governing access to and use of ReachFlow." };

export default function TermsPage() {
  return <LegalDocument eyebrow="Agreement" title="Terms of Service" summary="These terms govern access to ReachFlow. By creating an account, joining a workspace, or using the service, you agree to them on behalf of yourself and, where applicable, your organization.">
    <section><h2>1. Eligibility and authority</h2><p>You must be at least 18 years old and legally able to enter a binding agreement. If you use ReachFlow for an organization, you confirm that you are authorized to accept these terms for it.</p></section>
    <section><h2>2. Accounts and workspaces</h2><p>You must provide accurate account information, keep credentials secure, and promptly notify us of suspected unauthorized access. Workspace administrators control membership, roles, connected services, and workspace content. You are responsible for activity performed through your account and for maintaining appropriate access when team members change.</p></section>
    <section><h2>3. The service</h2><p>ReachFlow provides tools for prospect management, outreach preparation, messages and activity history, lead capture, automation, integrations, reporting, and related functionality. Features may evolve, and beta or preview features may be changed or discontinued. We may impose reasonable technical or usage limits to preserve security and reliability.</p></section>
    <section><h2>4. Customer data and instructions</h2><p>You retain ownership of information and materials submitted to ReachFlow. You grant ReachFlow a limited right to host, copy, transmit, transform, and otherwise process that content only as necessary to operate, secure, support, and improve the service and comply with law.</p><p>You are responsible for the legality, accuracy, quality, and source of your customer data; providing required privacy notices; honoring consent, opt-out, suppression, and deletion requests; and ensuring your instructions do not violate another person&apos;s rights.</p></section>
    <section><h2>5. Outreach and acceptable use</h2><p>You may not use ReachFlow to:</p><ul><li>send spam, deceptive communications, harassment, threats, or unlawful marketing;</li><li>contact people without a lawful basis or disregard opt-outs and do-not-contact records;</li><li>scrape, import, buy, or use personal information in violation of law, website terms, platform rules, or contractual restrictions;</li><li>impersonate another person or misrepresent message origin;</li><li>upload malware, probe security, bypass access controls or limits, or disrupt the service;</li><li>process highly sensitive data where ReachFlow has not expressly agreed to support it;</li><li>use the service or generated content to violate intellectual-property, privacy, publicity, consumer-protection, or other rights.</li></ul><p>ReachFlow helps organize outreach but does not determine whether a campaign is lawful. You remain responsible for compliance with marketing, privacy, telecommunications, and platform-specific rules that apply to you.</p></section>
    <section><h2>6. AI-generated content</h2><p>AI-assisted output may be inaccurate, incomplete, inappropriate, or similar to content generated for others. You must review output before sending or relying on it. You are responsible for the final message and its recipients. ReachFlow does not provide legal, financial, or professional advice through AI features.</p></section>
    <section><h2>7. Third-party services</h2><p>Connected services such as databases, automation platforms, social platforms, email providers, and AI providers are governed by their own terms. You authorize ReachFlow to exchange information with services you connect. We are not responsible for a third party&apos;s availability, changes, suspension, or handling of information.</p></section>
    <section><h2>8. Fees</h2><p>Paid plans, if offered, are governed by the pricing and billing terms shown when ordered. Unless stated otherwise, fees are due in advance, taxes are the customer&apos;s responsibility, and plan changes take effect as described at checkout. Nothing in these terms creates a paid obligation unless you select a paid offering.</p></section>
    <section><h2>9. Intellectual property and feedback</h2><p>ReachFlow and its software, design, documentation, branding, and underlying technology are protected by intellectual-property laws. Except for the limited right to use the service under these terms, no rights are transferred to you. If you provide feedback, we may use it without restriction or payment, provided we do not publicly identify you without permission.</p></section>
    <section><h2>10. Suspension and termination</h2><p>You may stop using ReachFlow at any time. We may restrict or suspend access when reasonably necessary to address security risk, unlawful conduct, nonpayment, material breach, or harm to the service or others. Where practical, we will provide notice and an opportunity to remedy. Termination does not remove obligations that by their nature should survive, including payment, ownership, disclaimers, and liability terms.</p><p>Deletion requests are handled as described on the <Link href="/data-deletion">Data Deletion page</Link>.</p></section>
    <section><h2>11. Disclaimers</h2><p>To the maximum extent permitted by law, ReachFlow is provided “as is” and “as available.” We do not warrant uninterrupted or error-free operation, any specific outreach result, lead quality, response rate, revenue outcome, or that generated content will meet your requirements. Nothing excludes warranties that cannot lawfully be excluded.</p></section>
    <section><h2>12. Limitation of liability</h2><p>To the maximum extent permitted by law, ReachFlow will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or loss of profits, revenue, goodwill, data, or business opportunity. ReachFlow&apos;s aggregate liability arising from the service will not exceed the amount paid for the service during the twelve months before the event giving rise to the claim, or US$100 if no fees were paid. These limits do not apply where prohibited by law.</p></section>
    <section><h2>13. Indemnity</h2><p>To the extent permitted by law, an organization using ReachFlow will defend and indemnify ReachFlow against third-party claims arising from its customer data, outreach, violation of law or platform rules, or material breach of these terms.</p></section>
    <section><h2>14. Governing terms and disputes</h2><p>An order form or separately signed agreement may identify governing law, venue, and additional commercial terms and will control if it conflicts with these terms. Otherwise, the governing law and forum will be those applicable to the ReachFlow operator, without regard to conflict-of-law principles. Mandatory consumer rights in a user&apos;s jurisdiction remain unaffected.</p></section>
    <section><h2>15. Changes and contact</h2><p>We may update these terms for legal, security, or product reasons. Material changes will be identified by an updated date and appropriate notice. Continued use after an update becomes effective constitutes acceptance where permitted by law.</p><p>Questions may be sent to <a href="mailto:legal@reachflow.app">legal@reachflow.app</a>. Privacy matters should be sent to <a href="mailto:privacy@reachflow.app">privacy@reachflow.app</a>.</p></section>
  </LegalDocument>;
}
