import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocument } from "@/components/legal/legal-document";

export const metadata: Metadata = { title: "Data Deletion | ReachFlow", description: "How to request deletion of information held through ReachFlow." };

export default function DataDeletionPage() {
  return <LegalDocument eyebrow="Privacy request" title="Delete your ReachFlow data" summary="Use these instructions to delete a ReachFlow account, agency workspace, prospect record, hosted-form submission, or connected Gmail data.">
    <section><h2>Before you submit a request</h2><p>Deletion is not always the same as opting out of outreach. If you only want communications to stop, say so in your request so a minimal suppression record can be kept to prevent future contact. Deleting that suppression record could make it harder to honor the opt-out.</p></section>
    <section><h2>Workspace account holders</h2><ol className="mt-3 space-y-2 [&_li]:ml-5 [&_li]:list-decimal"><li>Send an email from the address associated with your ReachFlow account to <a href="mailto:support@veilcode.studio?subject=ReachFlow%20account%20deletion%20request">support@veilcode.studio</a>.</li><li>Use the subject “ReachFlow account deletion request.”</li><li>Include your workspace name and whether you want only your profile removed or the entire workspace deleted.</li><li>If you are not the workspace owner or administrator, we may need authorization from one before deleting shared workspace content.</li></ol></section>
    <section><h2>Prospects and hosted-form respondents</h2><p>The ReachFlow customer that collected or uploaded your information normally controls that record. Contact the business or agency that sent you the message or published the form and ask it to delete or correct your information. If you cannot identify or reach that organization, email <a href="mailto:support@veilcode.studio?subject=Prospect%20data%20deletion%20request">support@veilcode.studio</a> with:</p><ul><li>your full name and the email, phone number, or social handle used;</li><li>the organization that contacted you, if known;</li><li>the form URL, message, or other context that helps locate the record;</li><li>whether you also want all future outreach stopped.</li></ul></section>
    <section><h2>Connected Gmail or Google account</h2><ol className="mt-3 space-y-2 [&_li]:ml-5 [&_li]:list-decimal"><li>Revoke ReachFlow&apos;s access from your Google Account&apos;s third-party connections page to stop future Google API access.</li><li>Email <a href="mailto:support@veilcode.studio?subject=Delete%20my%20connected%20Google%20data">support@veilcode.studio</a> from the address associated with your ReachFlow account.</li><li>Include your ReachFlow workspace name and the Gmail address that was connected.</li><li>State whether you want only the Google authorization and connection data deleted or also want Gmail-derived messages stored in the workspace deleted.</li></ol><p>Deleting connection data includes stored OAuth credentials and provider connection identifiers. Deleting synchronized messages may affect shared CRM history, analytics, reply detection, and audit records, so we may confirm the scope with a workspace administrator before removing shared content.</p></section>
    <section><h2>Other connected services</h2><p>Remove ReachFlow from the provider&apos;s account settings to stop future access, then email <a href="mailto:support@veilcode.studio?subject=Connected%20service%20data%20deletion">support@veilcode.studio</a>. Identify the workspace, provider, connected account, and any provider user ID available. Revoking a provider connection does not necessarily erase information already stored in ReachFlow, which is why the deletion request is a separate step.</p></section>
    <section><h2>What happens next</h2><p>We will acknowledge the request and may ask for information needed to verify identity, authority, or the records involved. We aim to complete verified requests within 30 days and will tell you if applicable law permits or requires more time. We will explain if specific information must be retained for security, fraud prevention, legal obligations, dispute resolution, or enforcement of agreements.</p><p>Deletion may remove account profiles, CRM records, form submissions, integration credentials, and associated operational data. Information may remain temporarily in protected backups until routine expiration. Aggregated or irreversibly de-identified information may remain because it no longer identifies a person. A minimal suppression record may also remain when necessary to ensure an opt-out continues to be honored.</p></section>
    <section><h2>Other privacy rights</h2><p>You may also request access, correction, portability, restriction, objection, or withdrawal of consent where those rights apply. Review the <Link href="/privacy">Privacy Policy</Link> for more information.</p></section>
  </LegalDocument>;
}
