import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocument } from "@/components/legal/legal-document";

export const metadata: Metadata = { title: "Data Deletion | ReachFlow", description: "How to request deletion of information held through ReachFlow." };

export default function DataDeletionPage() {
  return <LegalDocument eyebrow="Privacy request" title="Request data deletion" summary="You can ask ReachFlow or the organization that collected your information to delete it. The correct route depends on whether you are a workspace user, a prospect or form respondent, or a person who connected a third-party account.">
    <section><h2>Before you submit a request</h2><p>Deletion is not always the same as opting out of outreach. If you only want communications to stop, say so in your request so a minimal suppression record can be kept to prevent future contact. Deleting that suppression record could make it harder to honor the opt-out.</p></section>
    <section><h2>Workspace account holders</h2><ol className="mt-3 space-y-2 [&_li]:ml-5 [&_li]:list-decimal"><li>Send an email from the address associated with your ReachFlow account to <a href="mailto:privacy@reachflow.app?subject=ReachFlow%20account%20deletion%20request">privacy@reachflow.app</a>.</li><li>Use the subject “ReachFlow account deletion request.”</li><li>Include your workspace name and whether you want only your profile removed or the entire workspace deleted.</li><li>If you are not the workspace owner or administrator, we may need authorization from one before deleting shared workspace content.</li></ol></section>
    <section><h2>Prospects and hosted-form respondents</h2><p>The ReachFlow customer that collected or uploaded your information normally controls that record. Contact the business or agency that sent you the message or published the form and ask it to delete or correct your information. If you cannot identify or reach that organization, email <a href="mailto:privacy@reachflow.app?subject=Prospect%20data%20deletion%20request">privacy@reachflow.app</a> with:</p><ul><li>your full name and the email, phone number, or social handle used;</li><li>the organization that contacted you, if known;</li><li>the form URL, message, or other context that helps locate the record;</li><li>whether you also want all future outreach stopped.</li></ul></section>
    <section><h2>Facebook, Instagram, and other connected services</h2><p>Removing ReachFlow from a provider stops future access but may not automatically remove information previously stored. Remove the business integration from the provider&apos;s account settings, then email <a href="mailto:privacy@reachflow.app?subject=Connected%20service%20data%20deletion">privacy@reachflow.app</a> from the email associated with your ReachFlow account. Identify the workspace, provider, connected Page or account, and any provider user ID available.</p><p>This page can be used as ReachFlow&apos;s public <strong>Data Deletion Instructions URL</strong> for provider app configuration. A provider-specific automated deletion callback and confirmation-code status flow will be added when the native connection is implemented.</p></section>
    <section><h2>What happens next</h2><p>We acknowledge requests and may ask for information needed to verify identity, protect other workspace users, or locate the relevant record. Verified requests are handled within the time required by applicable law. We will explain if information must be retained for security, fraud prevention, legal obligations, dispute resolution, or enforcement of agreements.</p><p>Deletion may remove account profiles, CRM records, form submissions, connection credentials, and associated operational data. Information may remain temporarily in encrypted backups until routine expiration. Aggregated or irreversibly de-identified information may be retained because it no longer identifies a person.</p></section>
    <section><h2>Other privacy rights</h2><p>You may also request access, correction, portability, restriction, objection, or withdrawal of consent where those rights apply. Review the <Link href="/privacy">Privacy Policy</Link> for more information.</p></section>
  </LegalDocument>;
}
