-- REQUIRED IN SUPABASE SQL EDITOR: usage metering, compliance controls, and duplicate review.
-- Idempotent and safe to rerun.
CREATE TABLE IF NOT EXISTS public.plan_entitlements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),plan text NOT NULL,metric text NOT NULL,limit_value bigint,period text NOT NULL DEFAULT 'month',is_hard_limit boolean NOT NULL DEFAULT false,UNIQUE(plan,metric));
CREATE TABLE IF NOT EXISTS public.usage_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,metric text NOT NULL,quantity bigint NOT NULL DEFAULT 1,idempotency_key text,occurred_at timestamptz NOT NULL DEFAULT now(),metadata jsonb NOT NULL DEFAULT '{}'::jsonb,UNIQUE(org_id,idempotency_key));
CREATE TABLE IF NOT EXISTS public.retention_policies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,prospect_retention_days integer NOT NULL DEFAULT 730,message_retention_days integer NOT NULL DEFAULT 730,legal_hold boolean NOT NULL DEFAULT false,updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(org_id));
CREATE TABLE IF NOT EXISTS public.suppression_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,prospect_id uuid REFERENCES public.prospects(id) ON DELETE SET NULL,identity_type text NOT NULL,identity_value text NOT NULL,reason text NOT NULL,source text NOT NULL DEFAULT 'manual',created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz,UNIQUE(org_id,identity_type,identity_value));
CREATE TABLE IF NOT EXISTS public.consent_records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,prospect_id uuid NOT NULL REFERENCES public.prospects(id) ON DELETE CASCADE,status text NOT NULL CHECK(status IN ('granted','denied','withdrawn','unknown')),purpose text NOT NULL DEFAULT 'outreach',source text NOT NULL,recorded_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,recorded_at timestamptz NOT NULL DEFAULT now(),evidence text);
CREATE TABLE IF NOT EXISTS public.privacy_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,prospect_id uuid REFERENCES public.prospects(id) ON DELETE SET NULL,request_type text NOT NULL CHECK(request_type IN ('export','delete','correct')),status text NOT NULL DEFAULT 'open',requested_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,handled_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,notes text);
CREATE TABLE IF NOT EXISTS public.duplicate_candidates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,prospect_a_id uuid NOT NULL REFERENCES public.prospects(id) ON DELETE CASCADE,prospect_b_id uuid NOT NULL REFERENCES public.prospects(id) ON DELETE CASCADE,confidence integer NOT NULL CHECK(confidence BETWEEN 0 AND 100),matched_on text[] NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now(),reviewed_by uuid REFERENCES public.profiles(id),reviewed_at timestamptz,UNIQUE(org_id,prospect_a_id,prospect_b_id));
CREATE TABLE IF NOT EXISTS public.prospect_merge_log(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,source_prospect_id uuid,target_prospect_id uuid NOT NULL REFERENCES public.prospects(id) ON DELETE RESTRICT,source_snapshot jsonb NOT NULL,relationship_counts jsonb NOT NULL DEFAULT '{}'::jsonb,merged_by uuid NOT NULL REFERENCES public.profiles(id),merged_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS usage_events_org_time_idx ON public.usage_events(org_id,occurred_at DESC); CREATE INDEX IF NOT EXISTS suppression_org_identity_idx ON public.suppression_entries(org_id,identity_type,identity_value); CREATE INDEX IF NOT EXISTS duplicate_candidates_org_status_idx ON public.duplicate_candidates(org_id,status);
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['usage_events','retention_policies','suppression_entries','consent_records','privacy_requests','duplicate_candidates','prospect_merge_log'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I',t||'_select',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.organization_members m WHERE m.org_id=%I.org_id AND m.user_id=auth.uid()))',t||'_select',t,t); EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I',t||'_write',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.organization_members m WHERE m.org_id=%I.org_id AND m.user_id=auth.uid() AND m.role=''admin'')) WITH CHECK (EXISTS (SELECT 1 FROM public.organization_members m WHERE m.org_id=%I.org_id AND m.user_id=auth.uid() AND m.role=''admin''))',t||'_write',t,t,t); END LOOP; END $$;
ALTER TABLE public.plan_entitlements ENABLE ROW LEVEL SECURITY; DROP POLICY IF EXISTS plan_entitlements_read ON public.plan_entitlements; CREATE POLICY plan_entitlements_read ON public.plan_entitlements FOR SELECT TO authenticated USING(true);
INSERT INTO public.plan_entitlements(plan,metric,limit_value,period,is_hard_limit) VALUES ('free','prospects',500,'lifetime',false),('free','members',3,'lifetime',false),('free','imports',10,'month',false),('free','ai_generations',100,'month',false) ON CONFLICT(plan,metric) DO NOTHING;
INSERT INTO public.retention_policies(org_id) SELECT id FROM public.organizations ON CONFLICT(org_id) DO NOTHING;
